CREATE TABLE Fichas (
  COD_ID_FICHA INTEGER NOT NULL,
  NUM_FICHA INTEGER NOT NULL,
  PRIMARY KEY(COD_ID_FICHA)
);

CREATE TABLE Ejercicios (
  COD_EJERCICIO INTEGER NOT NULL AUTO_INCREMENT,
  EJERCICIO VARCHAR(20) NOT NULL,
  PRIMARY KEY(COD_EJERCICIO)
);

CREATE TABLE Tipos_Clientes (
  COD_TIPO_CLIENTE INTEGER NOT NULL AUTO_INCREMENT,
  TIPO_CLIENTE VARCHAR(20) NOT NULL,
  PRIMARY KEY(COD_TIPO_CLIENTE)
);

CREATE TABLE Clientes (
  IDENTIFICACION_CLIENTE DOUBLE NOT NULL,
  Tipo_Cliente_COD_TIPO_CLIENTE INTEGER NOT NULL,
  NOMBRE1 VARCHAR(20) NOT NULL,
  NOMBRE2 VARCHAR(20) NULL,
  APELLIDO1 VARCHAR(20) NOT NULL,
  APELLIDO2 VARCHAR(20) NOT NULL,
  Fichas_COD_ID_FICHA INTEGER NOT NULL,
  CORREO_SENA VARCHAR(45) NOT NULL,
  CONTRASEÑA VARCHAR(20) NOT NULL,
  PRIMARY KEY(IDENTIFICACION_CLIENTE),
  INDEX Clientes_FKIndex1(Tipo_Cliente_COD_TIPO_CLIENTE),
  INDEX Clientes_FKIndex2(Fichas_COD_ID_FICHA),
  FOREIGN KEY(Tipo_Cliente_COD_TIPO_CLIENTE)
    REFERENCES Tipos_Clientes(COD_TIPO_CLIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Fichas_COD_ID_FICHA)
    REFERENCES Fichas(COD_ID_FICHA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Registros_Asistencia (
  ID_REGISTRO INTEGER NOT NULL AUTO_INCREMENT,
  Clientes_IDENTIFICACION_CLIENTE DOUBLE NOT NULL,
  IDENTIFICACION_APRENDIZ DOUBLE NOT NULL,
  NOMBRE1_APRENDIZ VARCHAR(20) NOT NULL,
  NOMBRE2_APRENDIZ VARCHAR(20) NULL,
  APELLIDO1_APRENDIZ VARCHAR(20) NOT NULL,
  APELLIDO2_APRENDIZ VARCHAR(20) NOT NULL,
  CORREO_SENA_APRENDIZ VARCHAR(45) NOT NULL,
  FECHA DATE NOT NULL,
  PRIMARY KEY(ID_REGISTRO),
  INDEX Aprendices_Asistencia_FKIndex1(Clientes_IDENTIFICACION_CLIENTE),
  FOREIGN KEY(Clientes_IDENTIFICACION_CLIENTE)
    REFERENCES Clientes(IDENTIFICACION_CLIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Músculos (
  COD_MUSCULO INTEGER NOT NULL AUTO_INCREMENT,
  MUSCULO VARCHAR(20) NOT NULL,
  Clientes_IDENTIFICACION_CLIENTE DOUBLE NOT NULL,
  PRIMARY KEY(COD_MUSCULO),
  INDEX Músculos_FKIndex1(Clientes_IDENTIFICACION_CLIENTE),
  FOREIGN KEY(Clientes_IDENTIFICACION_CLIENTE)
    REFERENCES Clientes(IDENTIFICACION_CLIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Relación_Músculos_Ejercicios (
  Músculos_COD_MUSCULO INTEGER NOT NULL,
  Ejercicios_COD_EJERCICIO INTEGER NOT NULL,
  PRIMARY KEY(Músculos_COD_MUSCULO, Ejercicios_COD_EJERCICIO),
  INDEX Músculos_has_Ejercicios_FKIndex1(Músculos_COD_MUSCULO),
  INDEX Músculos_has_Ejercicios_FKIndex2(Ejercicios_COD_EJERCICIO),
  FOREIGN KEY(Músculos_COD_MUSCULO)
    REFERENCES Músculos(COD_MUSCULO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Ejercicios_COD_EJERCICIO)
    REFERENCES Ejercicios(COD_EJERCICIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


