CREATE TABLE Músculos (
  COD_MUSCULO INTEGER NOT NULL AUTO_INCREMENT,
  MUSCULO VARCHAR(20) NOT NULL,
  PRIMARY KEY(COD_MUSCULO)
);

CREATE TABLE Tipos_Clientes (
  COD_TIPO_CLIENTE INTEGER NOT NULL AUTO_INCREMENT,
  TIPO_CLIENTE VARCHAR(20) NOT NULL,
  PRIMARY KEY(COD_TIPO_CLIENTE)
);

CREATE TABLE Ficha_ProgramaF (
  COD_FICHA INTEGER NOT NULL,
  Programa_Formación VARCHAR(20) NOT NULL,
  PRIMARY KEY(COD_FICHA)
);

CREATE TABLE Ejercicios (
  COD_EJERCICIO INTEGER NOT NULL AUTO_INCREMENT,
  EJERCICIO VARCHAR(20) NOT NULL,
  PRIMARY KEY(COD_EJERCICIO)
);

CREATE TABLE Clientes (
  IDENTIFICACION_CLIENTE DOUBLE NOT NULL,
  Tipo_Cliente_COD_TIPO_CLIENTE INTEGER NOT NULL DEFAULT 1,
  NOMBRE1 VARCHAR(20) NOT NULL,
  NOMBRE2 VARCHAR(20) NULL,
  APELLIDO1 VARCHAR(20) NOT NULL,
  APELLIDO2 VARCHAR(20) NOT NULL,
  CORREO_SENA VARCHAR(45) NOT NULL,
  Ficha_ProgramaF_COD_FICHA INTEGER NOT NULL,
  CONTRASEÑA VARCHAR(15) NOT NULL,
  ANTECEDENTES_SALUD VARCHAR(255) NULL,
  PRIMARY KEY(IDENTIFICACION_CLIENTE),
  INDEX Clientes_FKIndex1(Tipo_Cliente_COD_TIPO_CLIENTE),
  INDEX Clientes_FKIndex2(Ficha_ProgramaF_COD_FICHA),
  FOREIGN KEY(Tipo_Cliente_COD_TIPO_CLIENTE)
    REFERENCES Tipos_Clientes(COD_TIPO_CLIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Ficha_ProgramaF_COD_FICHA)
    REFERENCES Ficha_ProgramaF(COD_FICHA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Relación_Músculos_Ejercicios (
  COD_MUSC_EJERC INTEGER NOT NULL AUTO_INCREMENT,
  Músculos_COD_MUSCULO INTEGER NOT NULL,
  Ejercicios_COD_EJERCICIO INTEGER NOT NULL,
  PRIMARY KEY(COD_MUSC_EJERC),
  INDEX Relación_Músculos_Ejercicios_FKIndex1(Músculos_COD_MUSCULO),
  INDEX Relación_Músculos_Ejercicios_FKIndex2(Ejercicios_COD_EJERCICIO),
  FOREIGN KEY(Músculos_COD_MUSCULO)
    REFERENCES Músculos(COD_MUSCULO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Ejercicios_COD_EJERCICIO)
    REFERENCES Ejercicios(COD_EJERCICIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Planificador Rutinas (
  COD_PLAN_RUT INTEGER NOT NULL AUTO_INCREMENT,
  Clientes_IDENTIFICACION_CLIENTE DOUBLE NOT NULL,
  Músculos_COD_MUSCULO INTEGER NOT NULL,
  PRIMARY KEY(COD_PLAN_RUT),
  INDEX Planificador Rutinas_FKIndex1(Clientes_IDENTIFICACION_CLIENTE),
  INDEX Planificador Rutinas_FKIndex2(Músculos_COD_MUSCULO),
  FOREIGN KEY(Clientes_IDENTIFICACION_CLIENTE)
    REFERENCES Clientes(IDENTIFICACION_CLIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Músculos_COD_MUSCULO)
    REFERENCES Músculos(COD_MUSCULO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Registros_Asistencia (
  ID_REGISTRO INTEGER NOT NULL AUTO_INCREMENT,
  Clientes_IDENTIFICACION_CLIENTE DOUBLE NOT NULL,
  IDENTIFICACION_APRENDIZ DOUBLE NOT NULL,
  NOMBRE1_APRENDIZ VARCHAR(20) NOT NULL,
  NOMBRE2_APRENDIZ VARCHAR(20) NULL,
  APELLIDO1_APRENDIZ VARCHAR(20) NOT NULL,
  APELLIDO2_APRENDIZ VARCHAR(20) NOT NULL,
  CORREO_SENA_APRENDIZ VARCHAR(45) NOT NULL,
  FECHA DATE NOT NULL,
  PRIMARY KEY(ID_REGISTRO),
  INDEX Aprendices_Asistencia_FKIndex1(Clientes_IDENTIFICACION_CLIENTE),
  FOREIGN KEY(Clientes_IDENTIFICACION_CLIENTE)
    REFERENCES Clientes(IDENTIFICACION_CLIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


